#!/bin/bash
# ~/.config/yadm/bootstrap

echo "vim-plug 설치 중..."
if [ ! -f ~/.vim/autoload/plug.vim ]; then
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# vim에서 플러그인을 자동으로 설치
vim +PlugInstall +qall

